server:
  port: 8071
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-alibaba-demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新。
          auto: update
          # 指定索引方式innodb
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 54e061f9-75c2-4150-9fbd-eb2f42d788d8
rocketmq:
  name-server: 127.0.0.1:9876
