server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-alibaba-demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          # 每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新。
          auto: update
          # 指定索引方式innodb
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比 100%，范围【0，1.0】
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 54e061f9-75c2-4150-9fbd-eb2f42d788d8
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址

# 开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
