server:
  port: 8081
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 不用自己创建数据库表，jpa帮我们创建表。没有则创建，有不创建
          auto: update
        # 指定索引方式innodb
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
